version: '3.8'
services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_JWT_SECRET_KEY=${FLASK_JWT_SECRET_KEY}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
